import { useState, useEffect } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Building2, CreditCard, Calendar, Check, Loader2, AlertTriangle, Crown, Sparkles, Zap, MessageSquare } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { useSubscription } from '@/hooks/useSubscription';
import { toast } from 'sonner';
import { format, formatDistanceToNow, isPast } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { cn } from '@/lib/utils';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { CardSubscriptionForm } from '@/components/subscription/CardSubscriptionForm';
import { SupportTab } from '@/components/support/SupportTab';

interface ClinicData {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  cnpj: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip_code: string | null;
  logo_url: string | null;
}

interface PlanDetails {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  price_monthly: number;
  features: string[];
  discount_pix_percent?: number | null;
  promo_price_monthly?: number | null;
  promo_active?: boolean | null;
  promo_label?: string | null;
}

const featureLabels: Record<string, string> = {
  agenda: 'Agenda de Consultas',
  pacientes: 'Gestão de Pacientes',
  pacientes_basico: 'Pacientes (Básico)',
  financeiro: 'Módulo Financeiro Completo',
  financeiro_basico: 'Financeiro Básico',
  relatorios: 'Relatórios Avançados',
  profissionais: 'Gestão de Profissionais',
  comissoes: 'Sistema de Comissões',
  estoque: 'Controle de Estoque',
  termos: 'Termos e Documentos',
  administracao: 'Administração',
  ponto: 'Controle de Ponto',
  multi_clinica: 'Multi-Clínicas',
};

const planIcons: Record<string, React.ReactNode> = {
  trial: <Calendar className="h-5 w-5" />,
  basico: <Zap className="h-5 w-5" />,
  profissional: <Sparkles className="h-5 w-5" />,
  premium: <Crown className="h-5 w-5" />,
};

export default function Settings() {
  const { user, session } = useAuth();
  const { subscription, refreshSubscription } = useSubscription();
  const [clinic, setClinic] = useState<ClinicData | null>(null);
  const [plan, setPlan] = useState<PlanDetails | null>(null);
  const [availablePlans, setAvailablePlans] = useState<PlanDetails[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [isUpgradeDialogOpen, setIsUpgradeDialogOpen] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState<PlanDetails | null>(null);
  const [upgradeNotes, setUpgradeNotes] = useState('');
  const [isSubmittingUpgrade, setIsSubmittingUpgrade] = useState(false);
  const [paymentMethod, setPaymentMethod] = useState<'card' | 'pix' | 'boleto'>('card');
  const [payerDocument, setPayerDocument] = useState('');
  const [paymentResult, setPaymentResult] = useState<{
    init_point?: string;
    qr_code?: string;
    qr_code_base64?: string;
    boleto_url?: string;
    amount?: number;
  } | null>(null);
  const [isCreatingPayment, setIsCreatingPayment] = useState(false);
  const [pixAutoGenerated, setPixAutoGenerated] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    cnpj: '',
    address: '',
    city: '',
    state: '',
    zip_code: '',
  });

  useEffect(() => {
    fetchData();
  }, [user]);

  // Real-time listener: refresh plan data when subscription or plan changes
  useEffect(() => {
    if (!user) return;

    const channel = supabase
      .channel('settings-subscription-changes')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'subscriptions' },
        () => { fetchData(); }
      )
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'plans' },
        () => { fetchData(); }
      )
      .subscribe();

    return () => { supabase.removeChannel(channel); };
  }, [user]);

  const fetchData = async () => {
    if (!user) return;

    try {
      // Get clinic_id for current user
      const { data: clinicUser } = await supabase
        .from('clinic_users')
        .select('clinic_id')
        .eq('user_id', user.id)
        .maybeSingle();

      if (!clinicUser) {
        setIsLoading(false);
        return;
      }

      // Fetch clinic data
      const { data: clinicData } = await supabase
        .from('clinics')
        .select('*')
        .eq('id', clinicUser.clinic_id)
        .maybeSingle();

      if (clinicData) {
        setClinic(clinicData);
        setFormData({
          name: clinicData.name || '',
          email: clinicData.email || '',
          phone: clinicData.phone || '',
          cnpj: clinicData.cnpj || '',
          address: clinicData.address || '',
          city: clinicData.city || '',
          state: clinicData.state || '',
          zip_code: clinicData.zip_code || '',
        });
      }

      // Fetch subscription with plan details
      const { data: subData } = await supabase
        .from('subscriptions')
        .select(`
          *,
          plans (
            id,
            name,
            slug,
            description,
            price_monthly,
            features,
            discount_pix_percent,
            promo_price_monthly,
            promo_active,
            promo_label
          )
        `)
        .eq('clinic_id', clinicUser.clinic_id)
        .maybeSingle();

      if (subData?.plans) {
        const planData = subData.plans as unknown as PlanDetails;
        setPlan({
          ...planData,
          features: Array.isArray(planData.features) 
            ? planData.features 
            : JSON.parse(planData.features as unknown as string || '[]')
        });
      }

      // Fetch available plans for upgrade
      const { data: plansData } = await supabase
        .from('plans')
        .select('id, name, slug, description, price_monthly, features, discount_pix_percent, promo_price_monthly, promo_active, promo_label')
        .eq('is_active', true)
        .neq('slug', 'trial')
        .order('price_monthly', { ascending: true });

      if (plansData) {
        setAvailablePlans(plansData.map((p: any) => ({
          ...p,
          features: Array.isArray(p.features)
            ? p.features
            : JSON.parse(p.features as unknown as string || '[]'),
        })));
      }
    } catch (error) {
      console.error('Error fetching data:', error);
      toast.error('Erro ao carregar dados');
    } finally {
      setIsLoading(false);
    }
  };

  const getBasePrice = (plan: PlanDetails) => {
    if (plan.promo_active && plan.promo_price_monthly) {
      return plan.promo_price_monthly;
    }
    return plan.price_monthly;
  };

  const getPriceForMethod = (plan: PlanDetails, method: 'card' | 'pix' | 'boleto') => {
    const base = getBasePrice(plan);
    if (method === 'pix' && plan.discount_pix_percent && plan.discount_pix_percent > 0) {
      return Math.max(0, base * (1 - plan.discount_pix_percent / 100));
    }
    return base;
  };

  const getAccessToken = async () => {
    const { data } = await supabase.auth.getSession();
    let accessToken = data.session?.access_token || session?.access_token;
    if (!accessToken) {
      const refreshed = await supabase.auth.refreshSession();
      accessToken = refreshed.data.session?.access_token;
    }
    return accessToken || null;
  };

  const handleSave = async () => {
    if (!clinic) return;

    setIsSaving(true);
    try {
      const { error } = await supabase
        .from('clinics')
        .update({
          name: formData.name,
          email: formData.email,
          phone: formData.phone || null,
          cnpj: formData.cnpj || null,
          address: formData.address || null,
          city: formData.city || null,
          state: formData.state || null,
          zip_code: formData.zip_code || null,
          updated_at: new Date().toISOString(),
        })
        .eq('id', clinic.id);

      if (error) throw error;

      toast.success('Dados atualizados com sucesso!');
      fetchData();
    } catch (error: any) {
      console.error('Error saving:', error);
      toast.error(error.message || 'Erro ao salvar dados');
    } finally {
      setIsSaving(false);
    }
  };

  const handleOpenUpgrade = (planToSelect?: PlanDetails) => {
    setSelectedPlan(planToSelect || null);
    setUpgradeNotes('');
    setIsUpgradeDialogOpen(true);
    setPaymentMethod('card');
    setPaymentResult(null);
    setPixAutoGenerated(false);
  };

  const handleCreatePayment = async () => {
    if (!user || !selectedPlan) return;

    setIsCreatingPayment(true);
    setPaymentResult(null);

    try {
      const accessToken = await getAccessToken();
      if (!accessToken) {
        toast.error('Sessão inválida. Faça login novamente.');
        return;
      }

      if (paymentMethod === 'card') {
        const { data, error } = await supabase.functions.invoke('mp-create-subscription', {
          headers: { Authorization: `Bearer ${accessToken}` },
          body: {
            plan_id: selectedPlan.id,
            user_id: user.id,
            notes: upgradeNotes || null,
          },
        });

        if (error) throw error;

        if (data?.init_point) {
          window.open(data.init_point, '_blank', 'noopener,noreferrer');
          toast.success('Checkout aberto. Finalize o pagamento para liberar o plano.');
        } else {
          toast.error('Não foi possível abrir o checkout.');
        }

        return;
      }

      const { data, error } = await supabase.functions.invoke('mp-create-payment', {
        headers: { Authorization: `Bearer ${accessToken}` },
        body: {
          plan_id: selectedPlan.id,
          user_id: user.id,
          payment_method: paymentMethod,
          notes: upgradeNotes || null,
          payer: {
            email: user.email,
            identification: payerDocument
              ? { type: 'CPF', number: payerDocument.replace(/\D/g, '') }
              : undefined,
          },
        },
      });

      if (error) throw error;

      setPaymentResult(data || null);
      toast.success('Pagamento gerado. Conclua para liberar o plano.');
    } catch (error) {
      console.error('Error creating payment:', error);
      toast.error('Erro ao gerar pagamento');
    } finally {
      setIsCreatingPayment(false);
    }
  };

  useEffect(() => {
    if (!isUpgradeDialogOpen || !selectedPlan) return;
    if (paymentMethod !== 'pix') {
      setPixAutoGenerated(false);
      return;
    }
    if (pixAutoGenerated || isCreatingPayment || paymentResult) return;
    setPixAutoGenerated(true);
    handleCreatePayment();
  }, [paymentMethod, isUpgradeDialogOpen, selectedPlan, pixAutoGenerated, isCreatingPayment, paymentResult]);

  const handleSubmitUpgradeRequest = async () => {
    if (!user || !selectedPlan) return;
    setIsSubmittingUpgrade(true);

    try {
      const { data: clinicUser } = await supabase
        .from('clinic_users')
        .select('clinic_id')
        .eq('user_id', user.id)
        .maybeSingle();

      if (!clinicUser) {
        toast.error('Clínica não encontrada');
        return;
      }

      const { data: subscriptionData } = await supabase
        .from('subscriptions')
        .select('id, plan_id')
        .eq('clinic_id', clinicUser.clinic_id)
        .maybeSingle();

      const { error } = await supabase.from('upgrade_requests').insert({
        clinic_id: clinicUser.clinic_id,
        subscription_id: subscriptionData?.id || null,
        requested_by: user.id,
        requested_plan_id: selectedPlan.id,
        current_plan_id: subscriptionData?.plan_id || null,
        notes: upgradeNotes || `Solicitação de upgrade para ${selectedPlan.name}`,
        status: 'pending',
      });

      if (error) throw error;

      await supabase.from('admin_notifications').insert({
        type: 'upgrade_request',
        title: 'Nova solicitação de upgrade',
        message: `Solicitação de upgrade para ${selectedPlan.name}`,
        reference_type: 'upgrade_request',
        reference_id: clinicUser.clinic_id,
      });

      toast.success('Solicitação enviada! Você pode efetuar o pagamento e enviar o comprovante.');
      setIsUpgradeDialogOpen(false);
      setSelectedPlan(null);
      setUpgradeNotes('');
    } catch (error) {
      console.error('Error submitting upgrade request:', error);
      toast.error('Erro ao enviar solicitação');
    } finally {
      setIsSubmittingUpgrade(false);
    }
  };

  const getStatusBadge = () => {
    if (!subscription) return null;
    
    const status = subscription.status;
    const isTrialExpired = status === 'trial' && subscription.trial_ends_at && isPast(new Date(subscription.trial_ends_at));

    if (isTrialExpired) {
      return <Badge variant="destructive">Trial Expirado</Badge>;
    }

    switch (status) {
      case 'trial':
        return <Badge variant="secondary">Trial</Badge>;
      case 'active':
        return <Badge className="bg-green-500 hover:bg-green-600">Ativo</Badge>;
      case 'suspended':
        return <Badge variant="destructive">Suspenso</Badge>;
      case 'cancelled':
        return <Badge variant="outline">Cancelado</Badge>;
      case 'expired':
        return <Badge variant="outline">Expirado</Badge>;
      default:
        return <Badge variant="outline">{status}</Badge>;
    }
  };

  if (isLoading) {
    return (
      <MainLayout>
        <div className="flex items-center justify-center h-96">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      </MainLayout>
    );
  }

  return (
    <MainLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Configurações</h1>
          <p className="text-muted-foreground mt-1">
            Gerencie os dados da sua clínica e visualize informações do seu plano
          </p>
        </div>

        <Tabs defaultValue="subscription" className="space-y-6">
          <TabsList className="grid w-full grid-cols-3 lg:w-auto lg:inline-grid">
            <TabsTrigger value="subscription" className="flex items-center gap-2">
              <CreditCard className="h-4 w-4" />
              <span>Meu Plano</span>
            </TabsTrigger>
            <TabsTrigger value="clinic" className="flex items-center gap-2">
              <Building2 className="h-4 w-4" />
              <span>Dados da Clínica</span>
            </TabsTrigger>
            <TabsTrigger value="support" className="flex items-center gap-2">
              <MessageSquare className="h-4 w-4" />
              <span>Suporte</span>
            </TabsTrigger>
          </TabsList>

          {/* Subscription Tab */}
          <TabsContent value="subscription" className="space-y-6">
            {/* Current Plan Card */}
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className={cn(
                      "h-12 w-12 rounded-full flex items-center justify-center",
                      plan?.slug === 'premium' ? "bg-amber-500/10 text-amber-500" : "bg-primary/10 text-primary"
                    )}>
                      {plan ? planIcons[plan.slug] || <CreditCard className="h-6 w-6" /> : <CreditCard className="h-6 w-6" />}
                    </div>
                    <div>
                      <CardTitle className="text-xl">{plan?.name || 'Sem Plano'}</CardTitle>
                      {plan?.description && (
                        <CardDescription>{plan.description}</CardDescription>
                      )}
                    </div>
                  </div>
                  {getStatusBadge()}
                </div>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Status Info */}
                <div className="grid gap-4 md:grid-cols-3">
                  <div className="rounded-lg border p-4">
                    <p className="text-sm text-muted-foreground">Status</p>
                    <p className="text-lg font-semibold mt-1 capitalize">
                      {subscription?.status === 'trial' ? 'Período de Teste' : subscription?.status === 'active' ? 'Ativo' : subscription?.status || '-'}
                    </p>
                  </div>
                  
                  {subscription?.status === 'trial' && subscription.trial_ends_at && (
                    <div className="rounded-lg border p-4">
                      <p className="text-sm text-muted-foreground">Trial Expira Em</p>
                      <p className="text-lg font-semibold mt-1">
                        {isPast(new Date(subscription.trial_ends_at)) ? (
                          <span className="text-destructive">Expirado</span>
                        ) : (
                          formatDistanceToNow(new Date(subscription.trial_ends_at), { 
                            addSuffix: true, 
                            locale: ptBR 
                          })
                        )}
                      </p>
                      <p className="text-xs text-muted-foreground mt-0.5">
                        {format(new Date(subscription.trial_ends_at), "dd/MM/yyyy 'às' HH:mm", { locale: ptBR })}
                      </p>
                    </div>
                  )}

                  <div className="rounded-lg border p-4">
                    <p className="text-sm text-muted-foreground">Valor Mensal</p>
                    <p className="text-lg font-semibold mt-1">
                      {plan 
                        ? getBasePrice(plan) === 0 
                          ? 'Gratuito' 
                          : `R$ ${getBasePrice(plan).toFixed(2).replace('.', ',')}`
                        : '-'
                      }
                    </p>
                    {plan?.promo_active && plan?.promo_price_monthly && plan.promo_price_monthly < plan.price_monthly && (
                      <p className="text-xs text-muted-foreground line-through">
                        R$ {plan.price_monthly.toFixed(2).replace('.', ',')}
                      </p>
                    )}
                  </div>
                </div>

                {/* Trial Warning */}
                {subscription?.status === 'trial' && subscription.trial_ends_at && !isPast(new Date(subscription.trial_ends_at)) && (
                  <div className="flex items-start gap-3 p-4 rounded-lg bg-warning/10 border border-warning/20">
                    <AlertTriangle className="h-5 w-5 text-warning flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="font-medium text-warning-foreground">Seu período de teste está ativo</p>
                      <p className="text-sm text-muted-foreground mt-1">
                        Após o término do trial, você precisará escolher um plano pago para continuar usando o sistema.
                      </p>
                    </div>
                  </div>
                )}

                <Separator />

                {/* Features */}
                <div>
                  <h3 className="font-semibold mb-4">Funcionalidades Incluídas</h3>
                  <div className="grid gap-2 sm:grid-cols-2">
                    {plan?.features.map((feature) => (
                      <div key={feature} className="flex items-center gap-2 text-sm">
                        <Check className="h-4 w-4 text-primary flex-shrink-0" />
                        <span>{featureLabels[feature] || feature}</span>
                      </div>
                    ))}
                    {(!plan?.features || plan.features.length === 0) && (
                      <p className="text-sm text-muted-foreground">Nenhuma funcionalidade disponível</p>
                    )}
                  </div>
                </div>

                {/* Upgrade Button */}
                {availablePlans.length > 0 && (
                  <div className="pt-4">
                    <Button className="gap-2" onClick={() => handleOpenUpgrade()}>
                      <Sparkles className="h-4 w-4" />
                      Solicitar Upgrade do Plano
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Available Plans */}
            {availablePlans.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle>Planos Disponíveis</CardTitle>
                  <CardDescription>
                    Escolha um plano e solicite o upgrade a qualquer momento.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4 md:grid-cols-3">
                    {availablePlans.map((p) => {
                      const basePrice = getBasePrice(p);
                      const pixPrice = getPriceForMethod(p, 'pix');

                      return (
                      <div key={p.id} className="rounded-lg border p-4 space-y-3">
                        <div className="flex items-center gap-2">
                          <div className={cn(
                            "h-8 w-8 rounded-full flex items-center justify-center",
                            p.slug === 'premium' ? "bg-amber-500/10 text-amber-500" : "bg-primary/10 text-primary"
                          )}>
                            {planIcons[p.slug] || <CreditCard className="h-4 w-4" />}
                          </div>
                          <div>
                            <p className="font-medium">{p.name}</p>
                            <p className="text-xs text-muted-foreground">
                              {p.promo_active && p.promo_price_monthly ? (
                                <>
                                  <span className="line-through mr-1">
                                    R$ {p.price_monthly.toFixed(2).replace('.', ',')}
                                  </span>
                                  R$ {basePrice.toFixed(2).replace('.', ',')} / mês
                                </>
                              ) : (
                                <>R$ {basePrice.toFixed(2).replace('.', ',')} / mês</>
                              )}
                            </p>
                            {p.discount_pix_percent && p.discount_pix_percent > 0 && (
                              <p className="text-xs text-emerald-600">
                                Pix {p.discount_pix_percent}% off: R$ {pixPrice.toFixed(2).replace('.', ',')}
                              </p>
                            )}
                          </div>
                        </div>
                        <ul className="space-y-1 text-sm">
                          {p.features.slice(0, 4).map((f) => (
                            <li key={f} className="flex items-center gap-2">
                              <Check className="h-4 w-4 text-primary flex-shrink-0" />
                              <span>{featureLabels[f] || f}</span>
                            </li>
                          ))}
                          {p.features.length > 4 && (
                            <li className="text-xs text-muted-foreground">+ {p.features.length - 4} recursos</li>
                          )}
                        </ul>
                        <Button variant="outline" className="w-full" onClick={() => handleOpenUpgrade(p)}>
                          Solicitar {p.name}
                        </Button>
                      </div>
                      );
                    })}
                  </div>
                </CardContent>
              </Card>
            )}
          </TabsContent>

          {/* Clinic Data Tab */}
          <TabsContent value="clinic" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Building2 className="h-5 w-5" />
                  Dados da Clínica
                </CardTitle>
                <CardDescription>
                  Atualize as informações da sua clínica
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Basic Info */}
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="name">Nome da Clínica *</Label>
                    <Input
                      id="name"
                      value={formData.name}
                      onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                      placeholder="Nome da clínica"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="email">Email *</Label>
                    <Input
                      id="email"
                      type="email"
                      value={formData.email}
                      onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                      placeholder="contato@clinica.com"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="phone">Telefone</Label>
                    <Input
                      id="phone"
                      value={formData.phone}
                      onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                      placeholder="(11) 99999-9999"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="cnpj">CNPJ</Label>
                    <Input
                      id="cnpj"
                      value={formData.cnpj}
                      onChange={(e) => setFormData({ ...formData, cnpj: e.target.value })}
                      placeholder="00.000.000/0000-00"
                    />
                  </div>
                </div>

                <Separator />

                {/* Address */}
                <div>
                  <h3 className="font-semibold mb-4">Endereço</h3>
                  <div className="grid gap-4 sm:grid-cols-2">
                    <div className="sm:col-span-2 space-y-2">
                      <Label htmlFor="address">Endereço</Label>
                      <Input
                        id="address"
                        value={formData.address}
                        onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                        placeholder="Rua, número, complemento"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="city">Cidade</Label>
                      <Input
                        id="city"
                        value={formData.city}
                        onChange={(e) => setFormData({ ...formData, city: e.target.value })}
                        placeholder="Cidade"
                      />
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="state">Estado</Label>
                        <Input
                          id="state"
                          value={formData.state}
                          onChange={(e) => setFormData({ ...formData, state: e.target.value })}
                          placeholder="UF"
                          maxLength={2}
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="zip_code">CEP</Label>
                        <Input
                          id="zip_code"
                          value={formData.zip_code}
                          onChange={(e) => setFormData({ ...formData, zip_code: e.target.value })}
                          placeholder="00000-000"
                        />
                      </div>
                    </div>
                  </div>
                </div>

                <div className="flex justify-end pt-4">
                  <Button onClick={handleSave} disabled={isSaving} className="gap-2">
                    {isSaving ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Salvando...
                      </>
                    ) : (
                      'Salvar Alterações'
                    )}
                  </Button>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Support Tab */}
          <TabsContent value="support" className="space-y-6">
            <SupportTab />
          </TabsContent>
        </Tabs>
      </div>

      <Dialog open={isUpgradeDialogOpen} onOpenChange={setIsUpgradeDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Solicitar Upgrade</DialogTitle>
            <DialogDescription>
              Escolha o plano e a forma de pagamento. Pix tem desconto e a liberação pode ser automática.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>Plano</Label>
              <Select
                value={selectedPlan?.id || ''}
                onValueChange={(v) => {
                  const planFound = availablePlans.find((p) => p.id === v) || null;
                  setSelectedPlan(planFound);
                }}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Selecione um plano" />
                </SelectTrigger>
                <SelectContent>
                  {availablePlans.map((p) => (
                    <SelectItem key={p.id} value={p.id}>
                      {p.name} - R$ {getBasePrice(p).toFixed(2).replace('.', ',')}/mês
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {selectedPlan && (
              <div className="rounded-lg border p-3 space-y-1">
                <div className="flex items-center justify-between">
                  <span className="font-medium">{selectedPlan.name}</span>
                  <span className="font-semibold text-primary">
                    R$ {getPriceForMethod(selectedPlan, paymentMethod).toFixed(2).replace('.', ',')}/mês
                  </span>
                </div>
                {selectedPlan.discount_pix_percent && paymentMethod === 'pix' && (
                  <p className="text-xs text-emerald-600">
                    Pix com {selectedPlan.discount_pix_percent}% off aplicado.
                  </p>
                )}
                {selectedPlan.promo_active && selectedPlan.promo_label && (
                  <p className="text-xs text-amber-600">{selectedPlan.promo_label}</p>
                )}
              </div>
            )}

            <div className="space-y-2">
              <Label>Método de pagamento</Label>
              <Select value={paymentMethod} onValueChange={(v) => setPaymentMethod(v as 'card' | 'pix' | 'boleto')}>
                <SelectTrigger>
                  <SelectValue placeholder="Selecione o método" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="card">Cartão</SelectItem>
                  <SelectItem value="pix">Pix</SelectItem>
                  <SelectItem value="boleto">Boleto</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {paymentMethod === 'boleto' && (
              <div className="space-y-2">
                <Label htmlFor="payerDocument">CPF do responsável</Label>
                <Input
                  id="payerDocument"
                  value={payerDocument}
                  onChange={(e) => setPayerDocument(e.target.value)}
                  placeholder="000.000.000-00"
                />
                <p className="text-xs text-muted-foreground">
                  Obrigatório para emissão do boleto.
                </p>
              </div>
            )}

            {paymentMethod === 'card' && selectedPlan && user?.email && (
              <CardSubscriptionForm
                amount={getPriceForMethod(selectedPlan, 'card')}
                planId={selectedPlan.id}
                payerEmail={user.email}
                userId={user.id}
                notes={upgradeNotes}
                accessToken={session?.access_token}
                onSuccess={() => {
                  setIsUpgradeDialogOpen(false);
                  setSelectedPlan(null);
                  setUpgradeNotes('');
                }}
              />
            )}

            <div className="space-y-2">
              <Label>Observações (opcional)</Label>
              <Textarea
                value={upgradeNotes}
                onChange={(e) => setUpgradeNotes(e.target.value)}
                placeholder="Ex: Vou pagar por boleto e envio comprovante."
                rows={3}
              />
            </div>

            {paymentResult && (
              <div className="space-y-3 rounded-lg border p-4">
                <p className="font-medium">Pagamento gerado</p>
                {paymentResult.qr_code_base64 && (
                  <div className="space-y-2">
                    <img
                      src={`data:image/png;base64,${paymentResult.qr_code_base64}`}
                      alt="QR Code Pix"
                      className="h-40 w-40"
                    />
                    {paymentResult.qr_code && (
                      <Button
                        type="button"
                        variant="outline"
                        onClick={() => navigator.clipboard.writeText(paymentResult.qr_code || '')}
                      >
                        Copiar código Pix
                      </Button>
                    )}
                  </div>
                )}
                {paymentResult.boleto_url && (
                  <Button asChild variant="outline">
                    <a href={paymentResult.boleto_url} target="_blank" rel="noreferrer">
                      Abrir boleto
                    </a>
                  </Button>
                )}
                {!paymentResult.qr_code_base64 && !paymentResult.boleto_url && paymentResult.init_point && (
                  <Button asChild variant="outline">
                    <a href={paymentResult.init_point} target="_blank" rel="noreferrer">
                      Abrir pagamento
                    </a>
                  </Button>
                )}
              </div>
            )}
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setIsUpgradeDialogOpen(false)}>
              Cancelar
            </Button>
            {paymentMethod !== 'card' && (
              <Button
                onClick={handleCreatePayment}
                disabled={
                  !selectedPlan ||
                  isCreatingPayment ||
                  (paymentMethod === 'boleto' && payerDocument.trim().length < 11)
                }
              >
                {isCreatingPayment ? 'Gerando...' : paymentMethod === 'pix' ? 'Gerar Pix' : 'Gerar pagamento'}
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </MainLayout>
  );
}
